### ISSUE TITLE
Site a mostrar NaN no lugar do nº de doses diarias

### ISSUE THREAD

**Issue by RevengeFNF** [diogotcorreia/covid19-pt-progress-bar#2]
![xTqSPzS](https://user-images.githubusercontent.com/940019/125354310-8eaa8100-e35b-11eb-9dd6-d282c8aaad26.png)

**Comment by diogotcorreia** [comment]
Obrigado pelo report, mas infelizmente não posso fazer nada ainda.
A DGS deixou de reportar os dados nos últimos dias para melhorar a contagem e só hoje é que se vai saber como ficou

Related: https://github.com/dssg-pt/covid19pt-data/issues/982

Assim que o [dataset que eu estou a usar](https://github.com/dssg-pt/covid19pt-data/blob/master/vacinas.csv) voltar ao ativo vou ver o que se pode fazer quanto a esses dias sem dados

**Comment by davipt** [comment]
Confirmo que não houve dados diários durante o fim de semana para que pudessem corrigir a plataforma e os valores inflacionados da ultima semana (carregamento dos valores das ilhas).

Os dados a partir de dia 12 (ontem, e hoje 13) voltaram ao normal.

**Comment by diogotcorreia** [comment]
Já atualizei o site.
Em vez de 1 dose e 2 doses passei a incluir "pessoas com pelo menos 1 dose" e "pessoas totalmente vacinadas", que tem em conta as vacinas de apenas 1 dose

**Comment by davipt** [comment]
As colunas "pessoas" e "vacinas" acertam com o relatório semanal (vacinas_detalhes.csv), e nos seis dias seguintes incrementam com o aumento diário do continente. Não é perfeito mas é mais realista para o panorama nacional, com ilhas, e com as janssen contabilizadas corretamente (assim como os recuperados com dose única). 

A OWID (e depois FT), entre outros, usam estes valores, portanto toda a ajuda é bem vinda caso se detecte algo estranho. O dia dos "281 mil vacinas por dia" devia ter feito logo trigger que also se passava, mas estávamos todos tão contentes com a vacinação a subir que nem ligámos.

Obrigado!
